Repository adopted-ember-addons/ember-changeset, pull requests merged in 2020-05, with the labels that each got.

#465 Ensure get doesnt take into account keys in CHANGES
  addon/index.js
  tests/unit/changeset-test.js
Labels: bug

#466 Leaf detection when merging sibling keys
  addon/index.js
  addon/utils/is-leaf.js
  tests/unit/changeset-test.js
Labels: bug, enhancement

#467 Use Ember.get if key is dot separated
  addon/index.js
  addon/utils/is-leaf.js
  tests/unit/changeset-test.js
Labels: enhancement

#473 Ensure dont lose sibling keys when ask for top level object and child…
  addon/index.js
  addon/utils/is-object.js
  tests/unit/changeset-test.js
Labels: bug

#475 Bump 0.4.7 validated-changeset
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhancement

#471 Safe set for setDeep
  addon/index.js
  package.json
  yarn.lock
Labels: bug

#479 Validate nested fields validate/0
  package.json
  tests/unit/changeset-test.js
  yarn.lock
Labels: WIP, bug

#481 Add isDirty tests
  tests/integration/main-test.js
Labels: enhancement

#484 Implement recursive object tree proxy to properly handle sibling keys
  addon/index.js
  package.json
  tests/integration/main-test.js
  tests/unit/changeset-test.js
  yarn.lock
Labels: WIP, bug, enhancement

#482 Failing test case for validating computed property
  package.json
  tests/unit/changeset-test.js
  yarn.lock
Labels: bug, enhancement

#487 New API - enum of keys to set isDirty state
  README.md
  package.json
  tests/integration/main-test.js
  yarn.lock
Labels: enhancement
