Repository adopted-ember-addons/ember-changeset, pull requests merged in 2020-02, with the labels that each got.

#391 validated-changeset - exit beta
  addon/-private/change.ts
  addon/-private/err.ts
  addon/-private/evented.ts
  addon/-private/notifier.ts
  addon/-private/validated-changeset.ts
  addon/helpers/changeset-get.js
  addon/helpers/changeset-get.ts
  addon/helpers/changeset-set.js
  addon/helpers/changeset.js
  addon/helpers/changeset.ts
  addon/index.js
  addon/index.ts
  addon/types/config.ts
  addon/types/evented.ts
  addon/types/index.ts
  addon/types/validation-result.ts
  addon/types/validator-action.ts
  addon/utils/assign.ts
  addon/utils/get-deep.ts
  addon/utils/get-key-values.ts
  addon/utils/handle-multiple-validations.ts
  addon/utils/is-changeset.ts
  addon/utils/is-object.js
  addon/utils/is-promise.ts
  addon/utils/key-in-object.ts
  addon/utils/merge-deep.js
  addon/utils/merge-nested.ts
  addon/utils/normalize-object.ts
  addon/utils/object-without.ts
  addon/utils/set-deep.ts
  addon/utils/take.ts
  addon/utils/validator-lookup.ts
  addon/utils/wrap.ts
  ember-cli-build.js
  package.json
  tests/dummy/app/components/changeset-form.js
  tests/unit/utils/assign-test.js
  tests/unit/utils/get-deep-test.js
  tests/unit/utils/is-changeset-test.js
  tests/unit/utils/is-promise-test.js
  tests/unit/utils/key-in-object-test.ts
  tests/unit/utils/merge-deep-test.js
  tests/unit/utils/merge-nested-test.js
  tests/unit/utils/normalize-object-test.js
  tests/unit/utils/object-without-test.js
  tests/unit/utils/set-deep-test.js
  tests/unit/utils/take-test.js
  tsconfig.json
  types/dummy/index.d.ts
  types/ember-data/types/registries/model.d.ts
  types/global.d.ts
  yarn.lock
Labels: enhancement

#423 Reexport validated-changeset types
  README.md
  addon/types/index.d.ts
Labels: bug, enhancement

#426 Set up release-it and lerna-changelog
  .release-it.json
  package-lock.json
  package.json
Labels: enhancement

#425 Moar types
  README.md
  addon/types/index.d.ts
  package-lock.json
  package.json
Labels: enhancement

#427 enhancement declare typings
  README.md
  index.d.ts
  package.json
Labels: enhancement

#428 enhancement Add types to app folder as well
  types/index.d.ts
Labels: bug, enhancement

#430 docs: set isChangeset import to validated-changeset
  README.md
Labels: docs, enhancement

#431 [BACKPORT v2] add fallback for getOwnPropertyDescriptors (#421)
  addon/utils/assign.ts
Labels: bug

#433 validated-changeset 0.2.1
  package.json
  yarn.lock
Labels: enhancement
