Repository adopted-ember-addons/ember-changeset, pull requests merged in 2020-06, with the labels that each got.

#490 Unwrap Proxy before sending into validatorFun
  package.json
  yarn.lock
Labels: bug

#493 Ensure Ember.get doesnt fail with undefined
  README.md
  package.json
  yarn.lock
Labels: bug

#497 Allow "value" as a key in a changeset object
  package.json
  yarn.lock
Labels: bug

#496 Update ember
  .eslintrc.js
  .template-lintrc.js
  .travis.yml
  addon/utils/merge-deep.js
  package.json
  testem.js
  tests/dummy/app/config/environment.d.ts
  tests/dummy/app/models/dog.js
  tests/dummy/app/models/profile.js
  tests/dummy/app/models/sync-user.js
  tests/dummy/app/models/user.js
  tests/integration/helpers/changeset-get-test.js
  tests/integration/helpers/changeset-get-test.ts
  tests/unit/changeset-test.js
  yarn.lock
Labels: enhancement

#500 Properly discern undefined key that was wiped out as a result of a change
  package.json
  yarn.lock
Labels: bug, enhancement

#503 Add failing test for accessing belongsTo relationship
  package.json
  tests/integration/helpers/changeset-get-test.js
  yarn.lock
Labels: bug

#506 Fix failing #set and #get for null belongsTo
  package.json
  tests/integration/helpers/changeset-get-test.js
  yarn.lock
Labels: bug, enhancement

#508 Unwrap proxy values before sending value into validation func and when passing through #get
  addon/index.js
  package.json
  tests/integration/main-test.js
  yarn.lock
Labels: Ember Data - relationships, bug, enhancement

#509 Add dependentKeyCompat to isValid/isInvalid
  addon/index.js
Labels: enhancement

#514 Throw error if merging e-d objects
  addon/utils/merge-deep.js
  tests/unit/utils/merge-deep-test.js
Labels: enhancement

#510 rm notifyPropertyChange from specific spots
  addon/index.js
Labels: enhancement
