Repository adopted-ember-addons/ember-changeset, pull requests merged in 2020-01, with the labels that each got.

#393 Fix TS type for changeset.errors
  addon/-private/validated-changeset.ts
  addon/types/index.ts
Labels: bug

#395 Add safeSet for Ember tracking context
  .travis.yml
  addon/utils/merge-deep.ts
  config/ember-try.js
  tests/dummy/app/components/changeset-form.ts
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/changeset-form.hbs
  tests/integration/components/changeset-form-test.js
Labels: bug

#397 Another safeSet for Ember happiness
  addon/utils/merge-deep.ts
  tests/dummy/app/components/changeset-form.ts
  tests/dummy/app/templates/components/changeset-form.hbs
  tests/integration/components/changeset-form-test.js
Labels: bug

#399 Collect errors correctly
  addon/-private/validated-changeset.ts
  addon/types/index.ts
  addon/utils/get-key-values.ts
  tests/unit/changeset-test.js
Labels: bug

#402 Properly manage error keys
  addon/utils/get-key-values.ts
  tests/unit/changeset-test.js
Labels: bug

#406 Failing test for ember data model.
  addon/utils/merge-deep.ts
  tests/dummy/app/models/profile.js
  tests/integration/main-test.js
Labels: bug

#404 Fix changeset get for nested properties with changes
  addon/-private/validated-changeset.ts
  tests/dummy/app/components/changeset-form.ts
  tests/dummy/app/templates/components/changeset-form.hbs
  tests/integration/components/changeset-form-test.js
Labels: bug

#412 Handle null cases
  addon/-private/validated-changeset.ts
  addon/utils/is-object.ts
  tests/dummy/app/components/changeset-form.ts
Labels: bug, enhancement

#413 Follow up: Check array type as well
  addon/-private/validated-changeset.ts
  tests/dummy/app/components/changeset-form.ts
  tests/unit/changeset-test.js
Labels: bug

#414 Bring back changeset-get for nested getter
  README.md
  addon/helpers/changeset-get.ts
  tests/dummy/app/templates/components/changeset-form.hbs
  tests/integration/components/changeset-form-test.js
  tests/unit/changeset-test.js
Labels: enhancement

#416 Ensure key in obj works with dot separated
  addon/-private/validated-changeset.ts
  addon/utils/key-in-object.ts
  app/utils/key-in-object.js
  tests/unit/utils/key-in-object-test.ts
Labels: bug

#417 Fix false values
  addon/-private/validated-changeset.ts
  tests/unit/changeset-test.js
Labels: bug

#418 Export Changeset class to allow overriding
  README.md
  addon/helpers/changeset.ts
  addon/index.ts
  addon/types/config.ts
  tests/dummy/app/components/changeset-form.ts
  tests/unit/changeset-test.js
Labels: enhancement

#409 Extend test coverage to sync relationships
  addon/-private/validated-changeset.ts
  tests/dummy/app/models/sync-user.js
  tests/integration/main-test.js
Labels: bug, enhancement

#421 add fallback for getOwnPropertyDescriptors
  addon/utils/assign.ts
Labels: bug
