Repository adopted-ember-addons/ember-changeset, pull requests merged in 2024-10, with the labels that each got.

#666 Use #let instead of deprecated #with in example
  README.md
Labels: docs

#671 Update the `repository` field of the `package.json` to point to the new location
  package.json
Labels: docs

#672 Update documentation urls to the new location
  README.md
  package.json
Labels: docs

#674 Bump GitHub actions
  .github/workflows/ci.yml
Labels: dependencies

#675 Bump ESLint to v8 and related plugins
  .eslintrc.js
  package-lock.json
  package.json
Labels: dependencies

#673 Bump prettier to v3 and fix lint
  .eslintrc.js
  .prettierignore
  .prettierrc.js
  addon/helpers/changeset.js
  addon/index.js
  addon/utils/is-object.js
  addon/utils/merge-deep.js
  addon/validated-changeset.js
  package-lock.json
  package.json
  tests/dummy/app/components/changeset-form.js
  tests/dummy/app/components/validated-form.js
  tests/dummy/config/targets.js
  tests/integration/components/changeset-form-test.js
  tests/integration/components/validated-form-test.js
  tests/integration/helpers/changeset-test.js
  tests/integration/main-test.js
  tests/unit/changeset-test.js
  tests/unit/utils/merge-deep-test.js
Labels: internal

#677 Replace `with` template helper with `let`
  tests/integration/helpers/changeset-test.js
Labels: internal

#676 Introduce stylelint
  .stylelintignore
  .stylelintrc.js
  package-lock.json
  package.json
Labels: dependencies

#678 Move components templates to colocated layout
  tests/dummy/app/components/changeset-form.hbs
  tests/dummy/app/components/validated-form.hbs
Labels: internal

#679 Explicit relationships options and ED store import in dummy app
  tests/dummy/app/models/dog.js
  tests/dummy/app/models/profile.js
  tests/dummy/app/models/sync-user.js
  tests/dummy/app/models/user.js
  tests/dummy/app/services/store.js
Labels: internal

#680 Bump ember-template-lint to v5 and fix errors
  package-lock.json
  package.json
  tests/integration/helpers/changeset-get-test.js
  tests/integration/helpers/changeset-test.js
Labels: dependencies

#683 Replace action helper with fn
  tests/dummy/app/components/.gitkeep
  tests/dummy/app/components/changeset-form.hbs
  tests/dummy/app/components/changeset-form.js
Labels: internal

#681 Sync with latest addon blueprint via ember-cli-update --to=4.12
  .ember-cli
  .eslintignore
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  CONTRIBUTING.md
  README.md
  config/environment.js
  ember-cli-build.js
  package-lock.json
  package.json
  tests/dummy/app/adapters/application.js
  tests/dummy/app/index.html
  tests/dummy/app/serializers/application.js
  tests/dummy/app/styles/app.css
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/helpers/index.js
  tests/index.html
  tests/integration/helpers/changeset-test.js
  vendor/.gitkeep
Labels: internal

#685 Replace Input component in tests with input element
  tests/integration/helpers/changeset-test.js
Labels: internal

#686 Bump eslint-plugin-qunit to v8
  .eslintrc.js
  package-lock.json
  package.json
Labels: dependencies

#687 Add missing changelog entries
  CHANGELOG.md
Labels: documentation

#682 Switch from release-it to release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .npmignore
  .release-it.json
  CHANGELOG.md
  RELEASE.md
  package-lock.json
  package.json
Labels: internal

#688 Drop support for Node.js 17 and below
  .github/workflows/ci.yml
  package.json
Labels: breaking

#684 Sync with latest addon blueprint via ember-cli-update --to=5.12
  .ember-cli
  .eslintignore
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .prettierignore
  .watchmanconfig
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  tests/dummy/app/components/changeset-form.js
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/helpers/index.js
  tests/unit/changeset-test.js
Labels: internal

#690 Update minimum supported Node.js version in README.md
  README.md
Labels: documentation

#691 Modernize readme examples
  README.md
Labels: documentation

#662 Pass through original mergeDeep error in cause property
  addon/utils/merge-deep.js
Labels: enhancement

#692 Remove unnecessary .gitkeep files
  addon/.gitkeep
  app/.gitkeep
  tests/integration/.gitkeep
  tests/unit/.gitkeep
Labels: internal
